### ISSUE TITLE
cannot import name 'Document'

### ISSUE THREAD

**Issue by tobi1993** [buriy/python-readability#118]
Hi there,
I am having an import error with
`from readability import Document`

- OS: Ubuntu
- Python 3.6.7
- installation: pip install readability-lxml

Please help

**Comment by buriy** [comment]
Do you have any file named "readability.py" in your code?

**Comment by tobi1993** [comment]
Yes that was the problem. Thank you very much! :)

**Comment by Yangzhihuabeijing** [comment]
Hi there,
I am having an import error with
    from readability import Document
ImportError: cannot import name 'Document'

centos centos-release-7-7.1908.0.el7.centos.x86_64
readability 0.7.1
python 3.6.10

please help

**Comment by stutteringp0et** [comment]
I have the same issue, but I already know why - I just don't know how to get past it.

In my script, I'm using both readability-lxml, and py-readability-metrics - both are loaded by the name "readability"

from readability import Document #readability-lxml
from readability import Readability #py-readability-metrics

**Comment by buriy** [comment]
I suggest to install one of the conflicting packages manually and rename their folder.
This package is only a handful of files -- not sure about the other one.
