### ISSUE TITLE
No chance for GitHub commit page?

### ISSUE THREAD

**Issue by 097115** [buriy/python-readability#157]
Would be great if `python-readability` could also properly display GitHub's commit pages :)

Now, it looks like this (this [commit](https://github.com/buriy/python-readability/commit/f166003f7040009a045311fa12bf2d4e6e8ed043), for example):

![](https://i.imgur.com/c59SZLk.png)

...which is almost it but unfortunately `+` and `-` signs are missing :)

The raw code for this part looks like this: 

    <tr data-hunk="84005d5c87f87695e3913a228b8e47a81a6f402a362102f2ebe1f0996d5b5a7c">
        <td id="diff-7ed266cfcd74a2fbfe39f2c9d6dd32f649bf5ca4733ae045e4631305482ff8fdL79" data-line-number="79" class="blob-num blob-num-context js-linkable-line-number"></td>
    
        <td id="diff-7ed266cfcd74a2fbfe39f2c9d6dd32f649bf5ca4733ae045e4631305482ff8fdR79" data-line-number="79" class="blob-num blob-num-context js-linkable-line-number"></td>
    
      <td class="blob-code blob-code-context">
        <span class="blob-code-inner blob-code-marker" data-code-marker=" ">        <span class="pl-k">return</span> <span class="pl-c1">None</span></span></td>
    </tr>
    
    <tr data-hunk="84005d5c87f87695e3913a228b8e47a81a6f402a362102f2ebe1f0996d5b5a7c">
        <td id="diff-7ed266cfcd74a2fbfe39f2c9d6dd32f649bf5ca4733ae045e4631305482ff8fdL80" data-line-number="80" class="blob-num blob-num-deletion js-linkable-line-number"></td>
    
        <td class="blob-num blob-num-deletion empty-cell"></td>
    
      <td class="blob-code blob-code-deletion">
        <span class="blob-code-inner blob-code-marker" data-code-marker="-">    <span class="pl-k">elif</span> <span class="pl-en">isinstance</span>(<span class="pl-s1">elements</span>, <span class="pl-s1 x x-first">re</span><span class="x">.</span><span class="pl-s1 x x-last">_pattern_type</span>):</span></td>
    </tr>
    
    <tr data-hunk="84005d5c87f87695e3913a228b8e47a81a6f402a362102f2ebe1f0996d5b5a7c">
        <td class="blob-num blob-num-addition empty-cell"></td>
    
        <td id="diff-7ed266cfcd74a2fbfe39f2c9d6dd32f649bf5ca4733ae045e4631305482ff8fdR80" data-line-number="80" class="blob-num blob-num-addition js-linkable-line-number"></td>
    
      <td class="blob-code blob-code-addition">
        <span class="blob-code-inner blob-code-marker" data-code-marker="+">    <span class="pl-k">elif</span> <span class="pl-en">isinstance</span>(<span class="pl-s1">elements</span>, <span class="pl-s1 x x-first x-last">pattern_type</span>):</span></td>
    </tr>

So, the corresponding parts already have those `data-code-marker="+"` and `data-code-marker="-"` in the `span` definitions... But not the text :)

And, by the way, huge thanks for this project, it's really incredible!

**Comment by buriy** [comment]
I see that the page is downloaded correctly, but the markup on the page is wrong for your purpose.
You can fix it with sed:

```python -m readability.readability -u https://github.com/buriy/python-readability/commit/f166003f7040009a045311fa12bf2d4e6e8ed043 | sed "s/data-code-marker=\"\([-+ ]\)\">/>\\1 /g" > 1.html```
