### ISSUE TITLE
I can't extract content from this Chinese article

### ISSUE THREAD

**Issue by nathanathan** [buriy/python-readability#47]
When I use readability on this article http://www.he.xinhuanet.com/news/2012-06/05/content_25346340.htm I am unable to extract any content. The encoding is gb2312, but I've converted it to unicode and the summary is still empty. The html elements don't have informative ids/classes, is there any way readability could handle documents like it?

**Comment by buriy** [comment]
The article in question works fine now. So closing this issue.
Thanks for patience.
