### ISSUE TITLE
Keep the <meta charset> tag or even add it 

### ISSUE THREAD

**Issue by gdamjan** [buriy/python-readability#51]
Html5 uses `<meta charset="UTF-8">`
HTML4 uses `<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />`

**Comment by buriy** [comment]
We use 

    RE_CHARSET = re.compile(br'<meta.*?charset=["\']*(.+?)["\'>]', flags=re.I)

capable of parsing both kind of tags (and two other ways to provide document encoding : https://github.com/buriy/python-readability/blob/master/readability/encoding.py#L6 )

Then we convert it to unicode / utf-8 and output it with utf-8 encoding.
