### ISSUE TITLE
Debug.info to debug.warning

### ISSUE THREAD

**Issue by c24b** [buriy/python-readability#69]
You should p)rovide an option to make readibility debug info silent while using it into a programm as you provide it in cmd line

I tried to rewrite logger.Level with no success
logging.getLogger("readability").setLevel(logging.WARNING)

**Comment by buriy** [comment]
Hi @c24b ,
Thanks for the report, I found a error here:
https://github.com/buriy/python-readability/blob/master/readability/readability.py#L23
should be 'readability.readability'.
Updated: https://github.com/buriy/python-readability/commit/c0d794fdd817ccce1d7490ff233f021329973eaf
Released version 0.6.1 with this change

**Comment by c24b** [comment]
Thanks for this :+1:
