### ISSUE TITLE
AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by oncletom** [buriy/python-readability#70]
Hello,

I faced the aforementioned error recently with the latest version of readability-lxml. This is part of the stacktrace:

```
    text = document_fromstring(Document(html,negative_keywords=['related']).summary()).text_content()
  File "build/bdist.linux-x86_64/egg/readability/readability.py", line 98, in __init__
    self.negative_keywords = compile_pattern(negative_keywords)
  File "build/bdist.linux-x86_64/egg/readability/readability.py", line 74, in compile_pattern
    elements = elements.split(',')
AttributeError: 'list' object has no attribute 'split'
```

And how it is used in our codebase:

```python
from readability.readability import Document

html = ...

text = document_fromstring(Document(html,negative_keywords=['related']).summary()).text_content()
```

**However**, this is **OK** if I pin to the version `0.3.0.6` of the library.

```bash
$ python --version
Python 2.7.6

$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

Any idea why such a breakage?

Thanks

cc @olivierthereaux

**Comment by buriy** [comment]
I guess I might have removed sending lists to negative_keywords and positive_keywords -- only comma-separated string can be now used.
Please use them separated with comma as a workaround for a while, but I'll fix it in the next version.

**Comment by olivierthereaux** [comment]
Might be worth changing the examples too. 

From:
```        Example:
            positive_keywords=["news-item", "block"]
            negative_keywords=["mysidebar", "related", "ads"]
```

To
```        Example:
            positive_keywords="news-item, block"
            negative_keywords= re.compile(r"mysidebar|related|ads")
```

https://github.com/buriy/python-readability/blob/master/readability/readability.py#L90

**Comment by oncletom** [comment]
Ah okay, it makes sense, thanks for this prompt feedback!

I do not mind changing the syntax but I'd do it only if the change in long-term. Otherwise I'd rather wait for the fix to be released.

As @olivierthereaux said, better to update the doc (README) and code comments if the change is long term, because we spent a bit of time yesterday, confused for the syntax not to work as documented.

**Comment by buriy** [comment]
I think, I will allow all three options (comma-separated, list and regex) because it won't cost much -- it should only run once on Document initialization.

**Comment by deanishe** [comment]
:+1: Whichever options are chosen, the docs should be right.

I couldn't figure out what the problem was because I was only looking at the docstring. As soon as I looked at the code, I realised the docstring is wrong: only regex or strings are allowed, not lists.
