### ISSUE TITLE
Detect whether page is suitable for applying readability

### ISSUE THREAD

**Issue by Andre0991** [buriy/python-readability#72]
Hi.

I'd like to know whether it's possible to make `python-readability` to indicate whether the page is question is suitable for applying readability.

For example, consider New York Times homepage. It's not supposed to be parsed by  `python-readability`.

Is it possible to check this?

Thanks.

**Comment by buriy** [comment]
Hi Andre0991,

python-readability was made for articles view pages: pages with only one large piece of text, which needs to be extracted.
I'm not sure how any check like this could be performed.
Try to think about a heuristics that will do this.
For example, you might subclass Document and override select_best_candidate function to check to analyse the returned fragments, count non-overlapping fragments and their lengths.
But most probably you won't be able to differentiate between article+large comments+snippets and a homepage with a number of article snippets.

**Comment by Andre0991** [comment]
Thanks for your answer, burly.

I think I'll have a loot at the heuristics used by Firefox readability implementation (Firefox currently shows the readability button only for certain pages).
