### ISSUE TITLE
-v/--verbose  not work

### ISSUE THREAD

**Issue by eromoe** [buriy/python-readability#77]
I add a print to see why not log:

-v 3
```
E:\Project>python -m readability.readability -v 3 -l readability_test.log  -u http://ecp.sgcc.com.cn/html/project/0140
02007/9990000000010135023.html
{'xpath': None, 'verbose': 1, 'url': 'http://ecp.sgcc.com.cn/html/project/014002007/9990000000010135023.html', 'negative
_keywords': None, 'browser': None, 'positive_keywords': None, 'log': 'readability_test.log'}
```

--verbose 3
```
E:\Project>python -m readability.readability -b --verbose 3 -l readability_test.log  -u http://ecp.sgcc.com.cn/html/proj
ect/014002007/9990000000010135023.html
{'xpath': None, 'verbose': 1, 'url': 'http://ecp.sgcc.com.cn/html/project/014002007/9990000000010135023.html', 'negative
_keywords': None, 'browser': True, 'positive_keywords': None, 'log': 'readability_test.log'}
```

since `parser.add_option('-v', '--verbose', action='count', default=0)` default is `0`,  don't understand why it become `1`...

env: windows 8 , python 2.7

**Comment by buriy** [comment]
I believe you need to write "-v -v -v" or "-vvv" to have verbosity level = 3.

**Comment by eromoe** [comment]
What? ... You are right, but this option is very weird I have never seen before. Wouldn't it be more clear and easy to use `int 3` ?

**Comment by buriy** [comment]
Well, there's no single standard. Both methods to define arguments are used in Linux commands.
For example, ssh uses this method:
 -v      Verbose mode.  Causes ssh to print debugging messages about its progress.  This is
             helpful in debugging connection, authentication, and configuration problems.  Multiple
             -v options increase the verbosity.  The maximum is 3.
