### ISSUE TITLE
Travis for CI

### ISSUE THREAD

**Issue by lwm** [buriy/python-readability#81]
Any interest in getting CI working for this project?

I am working on an OS project which will rely on this library and would like to see if your build is passing / failing more easily :)

I'd be happy to submit the PR for the `.travis.yml` file !

https://travis-ci.org/

**Comment by buriy** [comment]
Yes, thanks!
I used to test it with tox:
https://github.com/buriy/python-readability/blob/master/tox.ini  ,
https://github.com/buriy/python-readability/blob/master/Makefile#L13
That was enough for me so far.
