### ISSUE TITLE
Error in install and import

### ISSUE THREAD

**Issue by farhad-arjmand** [buriy/python-readability#83]
hi
i install readability but when import readability dosent work
>>> from readability.readability import Document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "readability.py", line 1, in <module>
    from readability.readability import Document
ImportError: No module named readability

but i can use command line :
python -m readability.readability -u http://pypi.python.org/pypi/readability-lxml

**Comment by buriy** [comment]
Hi Farhad,
just don't name your file "readability.py" -- instead of picking the library, it attempts to import your file again... And it has no inner "readability" submodule as you might guess... ;)
