### ISSUE TITLE
HTML isn't parsed when get_clean_html is called

### ISSUE THREAD

**Issue by Ostrea** [buriy/python-readability#86]
`get_clean_html` fails with `TypeError` when called right after document creation.
How to reproduce:
```python
from readability import Document
document = Document('Doesn't matter what to write here')
document.get_clean_html()
```
Looks like problem is in not calling `_html` [here](https://github.com/buriy/python-readability/blob/master/readability/readability.py#L143). HTML isn't parsed if I didn't call for example `title` and so it passes `None`. It fixes the problem if I call `_html` by hand.

**Comment by buriy** [comment]
`get_clean_html` is not a part of public API. It is supposed to be an internal method, which can be overridden in subclasses, for example, to disable DOM to text conversion and return winning DOM fragment instead:
https://github.com/buriy/python-readability/blob/master/readability/readability.py#L572

So, if you only need its functionality, you can just avoid using `Document` class completely.

    doc, encoding = build_doc(input)
    doc = html_cleaner.clean_html(doc)
    clean_attributes(tounicode(self.html))

In most cases, I would also suggest using `bleach` library instead -- it's small and highly customizable.

**Comment by Ostrea** [comment]
Thanks for your reply. Maybe add some comment to show that it isn't part of public api?

**Comment by buriy** [comment]
Improved docs (only in github version so far).
I'll consider renaming internal methods in next version ( 0.7 ).
