### ISSUE TITLE
Error when using a list for 'positive_keywords'

### ISSUE THREAD

**Issue by Bartvds** [buriy/python-readability#91]
Looks like the `positive_keywords` (and possible the negative version) doesn't really support a list/tuple as value.

The `compile_pattern` helper doesn't transform the list/tuple case into a regex, so later things raise when it tries to call `search()`/`match()` on the list.

Not sure what is intended here, I guess transforming into a regex?

**Comment by buriy** [comment]
Thanks, improved docs and implementation.
