### ISSUE TITLE
No module named langdata

### ISSUE THREAD

**Issue by sandeepsingh** [buriy/python-readability#95]
getting this error when i import this, 

from readability import Document

ImportError  Traceback (most recent call last)
<ipython-input-81-fb5ee06c2292> in <module>()
      1 #main content region from HTML web page
----> 2 from readability import Document
      3 
      4 # doc = Document(html)

anaconda2/lib/python2.7/site-packages/readability/__init__.py in <module>()
     26 import subprocess
     27 import collections
---> 28 from readability.langdata import LANGDATA
     29 if sys.version[0] >= '3':
     30         unicode = str  # pylint: disable=invalid-name,redefined-builtin

ImportError: No module named langdata

please help thanks

**Comment by buriy** [comment]
Hi Sandeep,

This readability package doesn't have module "readability.langdata".
You can check the source:
https://github.com/buriy/python-readability/tree/master/readability

This package is installed as "sudo pip install readability-lxml" ( see https://github.com/buriy/python-readability/ )

Maybe you have installed some other "readability" package instead?
I guess this one:
https://github.com/andreasvc/readability/tree/master/readability
