### ISSUE TITLE
Drop support for Python 2.6

### ISSUE THREAD

**Issue by cmermingas** [buriy/python-readability#97]
Python 2.6 has reached EOL:

https://www.python.org/dev/peps/pep-0361/#release-lifespan

Support can be dropped. I can do a pull request if you are ok with this.

**Comment by buriy** [comment]
Hi Carlos,

Do you think there is anything to remove?

**Comment by cmermingas** [comment]
Hi Yuri,

It's just in tox.ini and the comments in setup.py. It's not a big deal but there's a warning about python 2.6 support when I run the tests.

**Comment by hugovk** [comment]
The CI is also failing on latest master for Python 2.6 with:
```
ERROR:   py26: InterpreterNotFound: python2.6
```

And also for 3.3, which is also EOL:
```
ERROR:   py33: InterpreterNotFound: python3.3
```

https://travis-ci.org/hugovk/python-readability/builds/307586802

Here's the pip installs for readability-lxml from PyPI for the last month (via `pypinfo --percent --pip readability-lxml pyversion`) -- only 2 for 2.6, and nothing for 3.3.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   60.1% |          3,198 |
| 3.5            |   20.8% |          1,108 |
| 3.6            |   11.6% |            615 |
| 3.4            |    7.5% |            397 |
| 2.6            |    0.0% |              2 |

Please see PR https://github.com/buriy/python-readability/pull/100 to drop 2.6 and 3.3.
